#!/bin/bash
###########################################################
# Description:
#
#  Test suite for the resolv.conf parsing in ipconfig.sh and reachability.sh.
#  NetworkManager writes "# NOTE: ... nameservers." comments after the third
#  server; they must not be reported as DNS servers.
#
#  Both scripts query live interfaces, so only their resolv.conf lines are
#  extracted and run against a fixture file.
#
###########################################################

# MODULE/VERSION/COMMENTS are documentation.
# shellcheck disable=SC2034
MODULE=networkinfo
VERSION=1.0.0
COMMENTS="networkinfo resolv.conf parsing test suite"
DIR="$(dirname "$0")/../networkinfo"

TMPROOT="$(mktemp -d)"
trap 'rm -rf "$TMPROOT"' EXIT

IPCONFIG_DNS=$(grep -E '^(RESOLV_CONF|DNSSERVERS)=' "$DIR/ipconfig.sh")
REACHABILITY_DNS=$(grep -E '^(RESOLV_CONF=|read -r DNSSERVER1 )' "$DIR/reachability.sh")

tests_passed=0
tests_failed=0

assert_eq(){
    if [ "$1" == "$2" ]; then
        echo "PASS: $3"
        ((tests_passed++))
    else
        echo "FAIL: $3 (expected '$1', got '$2')"
        ((tests_failed++))
    fi
}

# ipconfig_dns <resolv.conf contents>: prints ipconfig.sh's DNS lines
ipconfig_dns(){
    printf '%b' "$1" > "$TMPROOT/resolv.conf"
    # shellcheck disable=SC2016
    RESOLV_CONF="$TMPROOT/resolv.conf" bash -c "$IPCONFIG_DNS"'
echo "$DNSSERVERS"'
}

# reachability_dns <resolv.conf contents>: prints the servers reachability.sh tests
reachability_dns(){
    printf '%b' "$1" > "$TMPROOT/resolv.conf"
    # shellcheck disable=SC2016
    RESOLV_CONF="$TMPROOT/resolv.conf" bash -c "$REACHABILITY_DNS"'
echo "$DNSSERVER1|$DNSSERVER2|$DNSSERVER3"'
}

NORMAL='# Generated by NetworkManager\nsearch example.com\nnameserver 192.168.1.1\nnameserver 192.168.1.2\n'
# More than three servers, as NetworkManager writes them, plus a commented-out
# server and a tab-separated line
MANY='# Generated by NetworkManager\n#nameserver 1.2.3.4\nnameserver 192.168.1.1\nnameserver\t192.168.1.2\nnameserver 2001:db8::1\n# NOTE: the libc resolver may not support more than 3 nameservers.\n# The nameservers listed below may not be recognized.\nnameserver 2001:db8::2\n'

assert_eq $'DNS: 192.168.1.1\nDNS: 192.168.1.2' "$(ipconfig_dns "$NORMAL")" "ipconfig.sh: two servers"
assert_eq $'DNS: 192.168.1.1\nDNS: 192.168.1.2\nDNS: 2001:db8::1\nDNS: 2001:db8::2' "$(ipconfig_dns "$MANY")" "ipconfig.sh: more than three servers"
assert_eq "" "$(ipconfig_dns "$MANY" | grep '^#')" "ipconfig.sh: no comment lines"
assert_eq "" "$(ipconfig_dns '# Generated by NetworkManager\n')" "ipconfig.sh: no servers"

assert_eq "192.168.1.1|192.168.1.2|" "$(reachability_dns "$NORMAL")" "reachability.sh: two servers"
assert_eq "192.168.1.1|192.168.1.2|2001:db8::1" "$(reachability_dns "$MANY")" "reachability.sh: first three of many servers"
assert_eq "||" "$(reachability_dns '# Generated by NetworkManager\n')" "reachability.sh: no servers"

echo
echo "Tests passed: $tests_passed, failed: $tests_failed"
[ "$tests_failed" -eq 0 ]
