#!/bin/bash

# Publish the WLAN Pi mDNS services with the current model and image version.
# The service file is generated here, not shipped: as a dpkg conffile that this
# script rewrote at every boot, each package change to it stopped upgrades at a
# conffile prompt (#113).

WLANPI_MODEL_CMD="${WLANPI_MODEL_CMD:-/usr/bin/wlanpi-model}"
WLANPI_MODEL_CACHE="${WLANPI_MODEL_CACHE:-/etc/wlanpi-model}"
WLANPI_RELEASE_FILE="${WLANPI_RELEASE_FILE:-/etc/wlanpi-release}"
SERVICE_FILE="${SERVICE_FILE:-/etc/avahi/services/wlanpi_announce.service}"

status=0
MODEL=""

# Prefer the model cached at boot by wlanpi-config-at-startup.sh (which this
# unit is ordered after). Running wlanpi-model probes USB/PCIe and can block on
# a stalled bus; the cache holds the same string the awk below extracts.
if [ -s "$WLANPI_MODEL_CACHE" ]; then
    MODEL=$(cat "$WLANPI_MODEL_CACHE")
elif [ -x "$WLANPI_MODEL_CMD" ]; then
    MODEL=$("$WLANPI_MODEL_CMD" | awk -F': +' '/^Model/ { print $2 }')
fi

# Still publish on failure, with the placeholders the shipped file used to
# carry, so apps keep discovering the device.
if [ -z "$MODEL" ]; then
    echo "Error: Empty model information" >&2
    MODEL="WLAN Pi"
    status=1
fi

VERSION=$(sed -n 's/^VERSION=//p' "$WLANPI_RELEASE_FILE" 2>/dev/null | head -n1)
if [ -z "$VERSION" ]; then
    echo "Error: Empty version information" >&2
    VERSION=0
    status=1
fi

# _http._tcp on 80 (nginx, redirects to the web UI) is what WiFi Explorer,
# Airtool and the WLAN Pi app browse for; _https._tcp is the Core API.
CONTENT=$(cat <<EOF
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<!-- Generated by wlanpi-avahi-service-update when avahi-daemon starts. -->
<service-group>
  <name replace-wildcards="yes">%h</name>
  <service>
    <type>_https._tcp</type>
    <port>31415</port>
    <txt-record>model=$MODEL</txt-record>
    <txt-record>ver=$VERSION</txt-record>
  </service>
  <service>
    <type>_http._tcp</type>
    <port>80</port>
    <txt-record>model=$MODEL</txt-record>
    <txt-record>ver=$VERSION</txt-record>
  </service>
  <service>
    <type>_ssh._tcp</type>
    <port>22</port>
    <txt-record>id=wlanpi</txt-record>
  </service>
</service-group>
EOF
)

# Rewrite only on change, atomically. avahi watches the directory and loads
# only *.service, so the dot-prefixed temp file is never published.
if [ "$(cat "$SERVICE_FILE" 2>/dev/null)" != "$CONTENT" ]; then
    TMP=$(mktemp "${SERVICE_FILE%/*}/.wlanpi_announce.XXXXXX") &&
        printf '%s\n' "$CONTENT" > "$TMP" &&
        chmod 644 "$TMP" &&
        mv -f "$TMP" "$SERVICE_FILE" || {
        rm -f "$TMP"
        echo "Error: Failed to write $SERVICE_FILE" >&2
        exit 1
    }
fi

exit "$status"
