name: Build and deploy to packagecloud

on:
  # Allow manual runs of workflow from Actions tab
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'debian/changelog'

jobs:
  sbuild:
    runs-on: 'ubuntu-20.04'

    strategy:
      matrix:
        distro: [buster,bullseye]
        arch: [armhf,arm64]

    environment: PACKAGECLOUD

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Debian package
        uses: wlan-pi/sbuild-debian-package@main
        id: build-debian-package
        with:
          distro: ${{ matrix.distro }}
          arch: ${{ matrix.arch }}

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: wlanpi-profiler-${{ matrix.distro }}-${{ matrix.arch }}
          path: ${{ steps.build-debian-package.outputs.deb-package }}

      - name: Upload package to packagecloud
        uses: danielmundi/upload-packagecloud@main
        with:
          package-name: ${{ steps.build-debian-package.outputs.deb-package }}
          packagecloud-username: wlanpi
          packagecloud-repo: dev
          packagecloud-distrib: raspbian/${{ matrix.distro }}
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}

  slack-workflow-status:
    if: always()
    name: Post Workflow Status to Slack
    needs:
      - sbuild
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: '#common'
          name: 'WLAN Pi CI Bot'